### ISSUE TITLE
Typo in name MIGHT not be allowed on poggit.

### ISSUE THREAD

**Issue by TheDeibo** [ElementalMinecraftGaming/WorldTools#1]
Hi. Unsure if this is a typo or not. 
If it is not a typo then it so be it. 

You put "Infint", which is looks obvious that its a typo.
Don't you mean, "Infinite"

**Comment by ElementalMinecraftGaming** [comment]
We are changing the name anyway XD

**Comment by ElementalMinecraftGaming** [comment]
Renaming to One In The Chamber (Reboot)
